
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>StreamsDemoApp</RootNamespace>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
        <PackageReference Include="MongoDB.Driver" Version="2.24.0" />
<!--        for fake data -->
        <PackageReference Include="Bogus" Version="35.4.0" />
        <PackageReference Include="Cistern.ValueLinq" Version="0.1.14" />

    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
